### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by yfu** [cansysbio/ConsensusTME#1]
Hi cansysbio,

I've read your nicely written preprint on bioRiv, which led me to this repository. But I could not find the immune cell content estimated by ConsensusTME. Could you kindly point me to the data?

Thanks in adavance!
Yu Fu

**Comment by olliecast** [comment]
Hi Yu,

Thank you for your positive feedback. While the manuscript is under review for publication we are currently keeping some of the data as available on request. This is mainly since we feel it would be irresponsible to make this data publicly available before our work has undergone the peer-review process. If you send a request to the corresponding author (Alejandro.JimenezSanchez@cruk.cam.ac.uk) & myself (Oliver.Cast@cruk.cam.ac.uk) we'd be happy to share this and any other data you'd find helpful!

Thank you for the interest in our work!

Ollie Cast

**Comment by olliecast** [comment]
Will re-open this issue for now until the data is committed following review.
