### ISSUE TITLE
Range score

### ISSUE THREAD

**Issue by imendizabalCIC** [cansysbio/ConsensusTME#3]
Hello,

Depending on the input data type (RNA-seq, array) and normalization methods I sometimes get the enrichment score as values ranging from 0 to 1 whereas others I get values that seem to range from -1 to 1. Do these look OK or are the scores supposed to range within certain positive values?

Also, in the paper it is mentioned "ConsensusTME NES scores are imputed primarily for comparison of scores relatively across samples. Similar to another ssGSEA-based method, xCell, ConsensusTME, and NES scores also resemble absolute scores, which would allow comparison across cell types; however, currently this has not been benchmarked (13)."  I was wondering if you have any update on whether we can interpret the consensusTME estimates in terms of relative cell-type abundances.

Thank you very much for you help,

Isabel

**Comment by olliecast** [comment]
Hi Isabel,

That is indeed normal and a common question raised to us. Since the enrichment scores reflect where the genes in the gene set are in relation to all other genes if they mainly have expression lower than the median gene expression negative enrichment scores can be produced. I think we need to look at changing the way this is reported as negative scores are still valid, representing a lower level of infiltration rather than negative levels of infiltration which isn't very intuitive currently. 

In regards to the second question we have done a small amount testing in the context of purely the relative cell-type abundances and while ConsensusTME scores do reflect the broad patterns in cell type abundances if comparing across cell types is your main question of interest I would recommend the regression based approaches like CIBERSORTx that have been optimised for this kind of analysis.

Hope this helps,

Ollie
